# Generated by Django 2.2 on 2020-06-25 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0002_auto_20200626_0152'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='auth_user',
            new_name='User',
        ),
    ]
